### ISSUE TITLE
Error when following instructions

### ISSUE THREAD

**Issue by chrisharrison** [lynnaloo/sails-vagrant#2]
After following the instructions and running `sails lift` - the following error occurs:

`info: Starting app...

info:
info:                .-..-.
info:
info:    Sails              <|    .-..-.
info:    v0.12.3             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------'
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info:
info: Server lifted in `/home/vagrant/dev/personaljs`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: -------------------------------------------------------
debug: :: Thu Jul 14 2016 14:48:15 GMT+0000 (UTC)

debug: Environment : development
debug: Port        : 1337
debug: -------------------------------------------------------
error: ** Grunt :: An error occurred. **
error:
------------------------------------------------------------------------
Aborted due to warnings.
Loading "less.js" tasks...ERROR
>> Error: Cannot find module 'lodash'
Warning: Task "less:dev" not found.
------------------------------------------------------------------------

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error:
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error:
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error:
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `/home/vagrant/dev/personaljs/.tmp` ?
error:
error:      If you think this might be the case, try running:
error:      sudo chown -R 1000 /home/vagrant/dev/personaljs/.tmp
`

**Comment by lynnaloo** [comment]
I'm so sorry, Chris! This repository is SO out of date and I haven't used Sails in years now. I'll put something in the README to let everyone know that I haven't touched this in a while.

Are you using Windows? If so, it could be a permissions issue and make sure that you run `vagrant up` in an administrator shell. It's also possible it's a problem with this version of Sails.js.

**Comment by chrisharrison** [comment]
Right, OK. Didn't realise this was not actively maintained. Thanks for getting back to me though.

I'll probably just create a new Vagrant environment for Sails which has all the latest versions in it.

**Comment by lynnaloo** [comment]
I think a big issue with this is the Node version: https://github.com/lynnaloo/sails-vagrant/blob/master/puppet/manifests/default.pp#L3. If you're interested in maintaining this, I'd happily give you the power 💪. I think it's a matter of updating the default Node version and making sure my globals in Puppet match the current Sails setup.
